language: java
jdk:
  - openjdk8


# * Travis CI를 어느 브랜치가 푸시될떄 수행할지 지정 #
# * 현재 옵션은 오직 master 브랜치에 PUSH될 떄 수행 #
branches:
  only:
    - master

#Travis CI 서버의 home
# cache 그레이들을 통해 의존성을 받게되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때 부터 받지않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    -
before_install:
  - chomod +x gradlew

# master 브랜치에 푸시되었을 때 수행하는 명령어
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - kks7824@gmail.com
