version: 0.0
# CodeDeploy 버전 : 프로젝트 버전이 아니므로 0.0 이외의 다른 버전을 사용하면 오류 발생

os: linux
files:
  - source: /
    # CodeDeploy에서 전달해준 파일 중 destination으로 이동시킬 대상을 지정
    destination: /home/ec2-user/app/step2/zip/
    # source 에서 지정된 파일을 받을 위치
    # 이후 Jar를 실행하는 등은 destination에 옮겨진 파일들로 진행

    overwrite: yes
    # 기존에 파일들이 있으면 overWrite 여부

